services:
  backend:
    image: node:16
    container_name: chat-backend
    command: bash
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    networks:
      - chat-network
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: chat-db
      JWT_SECRET: secret
  db:
    image: postgres:latest
    container_name: chat-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_app_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:latest
    container_name: chat-redis
    volumes:
      - ./backend/data-redis:/data
    ports:
      - "6379:6379"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
